# Generated by Django 3.1 on 2020-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncmentsArtTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncmentsScienceTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=32)),
            ],
        ),
    ]
