# Generated by Django 3.1 on 2020-08-28 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnouncmentsArtTool',
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='announcementType',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='isHelper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='isPayment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='isWorker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='place',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='tags',
            field=models.TextField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='timeToEnd',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
