# Generated by Django 3.1 on 2020-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20200828_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcmentssciencetool',
            name='isPayment',
            field=models.BooleanField(default=False),
        ),
    ]
