# Generated by Django 3.1 on 2020-08-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20200828_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='announcementType',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='author',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='isHelper',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='isPayment',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='isWorker',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='place',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='announcmentssciencetool',
            name='timeToEnd',
        ),
    ]
