# Generated by Django 3.1 on 2020-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcmentssciencetool_announcementtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcmentssciencetool',
            name='announcementType',
            field=models.CharField(default=False, max_length=4),
        ),
    ]
