# Generated by Django 3.1 on 2020-08-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20200828_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcmentssciencetool',
            name='announcementType',
            field=models.CharField(max_length=4),
        ),
    ]
