# Generated by Django 3.1 on 2020-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20200828_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcmentssciencetool',
            name='announcementType',
            field=models.TextField(max_length=4),
        ),
    ]
