# Generated by Django 3.1 on 2020-08-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20200828_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcmentssciencetool',
            old_name='announcementType',
            new_name='announcement_type',
        ),
    ]
