# Generated by Django 3.1 on 2020-08-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_remove_announcmentssciencetool_announcement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='announcementType',
            field=models.TextField(default=False, max_length=4),
        ),
    ]
