# Generated by Django 3.1 on 2020-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_announcmentssciencetool_isworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='isHelper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='isPayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='place',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='tags',
            field=models.TextField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='timeToEnd',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
