# Generated by Django 3.1 on 2020-08-28 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0016_auto_20200828_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcmentssciencetool',
            name='createAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
